[package]
name = "enum_display"
version = "0.1.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
categories = ["rust-patterns"]
description = "derive(EnumDisplay)"
documentation = "https://docs.rs/thiserror"
edition = "2018"
keywords = ["error", "error-handling", "derive"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/dtolnay/thiserror"
rust-version = "1.31"

[dependencies]
thiserror-impl = { version = "=1.0.35", path = "impl" }

[dev-dependencies]
anyhow = "1.0.65"
ref-cast = "1.0"
rustversion = "1.0"
trybuild = { version = "1.0.49", features = ["diff"] }

[workspace]
members = ["impl"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
